#Step 1: reading in the data

testX_test <- read.table("UCI HAR Dataset 2/test/X_test.txt")
testSubject_test <- read.table("UCI HAR Dataset 2/test/subject_test.txt")
testY_test <- read.table("UCI HAR Dataset 2/test/y_test.txt")
trainX_train <- read.table("UCI HAR Dataset 2/train/X_train.txt")
trainY_train <- read.table("UCI HAR Dataset 2/train/y_train.txt")
trainSubject_train <- read.table("UCI HAR Dataset 2/train/subject_train.txt")
trainSubject_train <- read.table("UCI HAR Dataset 2/activity_labels.txt")
trainSubject_train <- read.table("UCI HAR Dataset 2/train/subject_train.txt")
activitylabels <- read.table("UCI HAR Dataset 2/activity_labels.txt")
features <- read.table("UCI HAR Dataset 2/features.txt")

#Step 2: Constructing the data table

combTest <- cbind(testSubject_test, testY_test, testX_test)
combTrain <- cbind(trainSubject_train, trainY_train, trainX_train)
combTT <- rbind(combTest, combTrain)
newcolnames <- features[,2]
newcolnames <- as.vector(newcolnames)
newcolnames <- c("subject", "activity", newcolnames)
colnames(combTT) <- c(newcolnames)

#Step 3: Extracting only mean and standard deviation columns

meanSDcols <- c(1, 2, 3:8, 43:48, 83:88, 123:128, 163:168, 203, 204, 216, 217, 229, 230, 242, 243, 255, 256, 268:273, 347:352, 426:431, 505, 506, 518, 519, 531, 532, 544, 545)
meanSDTable <- combTT[,meanSDcols]
activity.names <- as.character(activitylabels[,2])
meanSDTable[,2] <- activity.names[meanSDTable[,2]]
meanSDTable[,2] <- as.factor(meanSDTable[,2])
meanSDTable[,1] <- as.integer(meanSDTable[,1])

#Step 4: Adding sensible column names

finalcolnames <- c("subject", "activity", "TimeBodyAcceleration-Mean-X", "TimeBodyAcceleration-Mean-Y", "TimeBodyAccelerationMean-Z", "TimeBodyAccelerationSTD-X", "TimeBodyAccelerationSTD-Y", "TimeBodyAccerlationSTD-Z", "TimeGravityAccelerationMean-X", "TimeGravityAccelerationMean-Y", "TimeGravityAccelerationMean-Z", "TimeGravityAccelerationSTD-X", "TimeGravityAccelerationSTD-Y", "TimeGravityAccelerationSTD-Z", "TimeBodyAccelerationJerkMean-X", "TimeBodyAccelerationJerkMean-Y", "TimeBodyAccelerationJerkMean-Z", "TimeBodyAccelerationJerkSTD-X", "TimeBodyAccelerationJerkSTD-Y", "TimeBodyAccelerationJerkSTD-Z", "TimeBodyGyroMean-X", "TimeBodyGyroMean-Y", "TimeBodyGyroMean-Z", "TimeBodyGyroSTD-X", "TimeBodyGyroSTD-Y", "TimeBodyGyroSTD-Z", "TimeBodyGyroJerkMean-X", "TimeBodyGyroJerkMean-Y", "TimeBodyGyroJerkMean-Z", "TimeBodyGyroJerkSTD-X", "TimeBodyGyroJerkSTD-Y", "TimeBodyGyroJerkSTD-Z", "TimeBodyAccelerationMagnitudeMean", "TimeBodyAccelerationMagnitudeSTD", "TimeGravityAccelerationMagnitudeMean", "TimeGravityAccelerationMagnitureSTD", "TimeBodyAccelerationJerkMagnitureMean", "TimeBodyAccelerationJerkMagnitureSTD", "TimeBodyGyroMagnitureMean", "TimeBodyGyroMagnitureSTD", "TimeBodyGyroJerkMagnitudeMean", "TimeBodyGyroJerkMagnitudeSTD", "FreqBodyAcceleration-Mean-X", "FreqBodyAcceleration-Mean-Y", "FreqBodyAccelerationMean-Z", "FreqBodyAccelerationSTD-X", "FreqBodyAccelerationSTD-Y", "FreqBodyAccerlationSTD-Z", "FreqBodyAccelerationJerkMean-X", "FreqBodyAccelerationJerkMean-Y", "FreqBodyAccelerationJerkMean-Z", "FreqBodyAccelerationJerkSTD-X", "FreqBodyAccelerationJerkSTD-Y", "FreqBodyAccelerationJerkSTD-Z", "FreqBodyGyroMean-X", "FreqBodyGyroMean-Y", "FreqBodyGyroMean-Z", "FreqBodyGyroSTD-X", "FreqBodyGyroSTD-Y", "FreqBodyGyroSTD-Z", "FreqBodyAccelerationMagnitudeMean", "FreqBodyAccelerationMagnitudeSTD", "FreqBodyAccelerationJerkMagnitureMean", "FreqBodyAccelerationJerkMagnitureSTD", "FreqBodyGyroMagnitureMean", "FreqBodyGyroMagnitureSTD", "FreqBodyGyroJerkMagnitudeMean", "FreqBodyGyroJerkMagnitudeSTD" )

colnames(meanSDTable) <- finalcolnames

#Step 5: Subsetting by combinations of subject and activity

W1 <- colMeans(meanSDTable[meanSDTable$subject==1 & meanSDTable$activity=="WALKING",][3:68])
WU1 <- colMeans(meanSDTable[meanSDTable$subject==1 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD1 <- colMeans(meanSDTable[meanSDTable$subject==1 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI1 <- colMeans(meanSDTable[meanSDTable$subject==1 & meanSDTable$activity=="SITTING",][3:68])
ST1 <- colMeans(meanSDTable[meanSDTable$subject==1 & meanSDTable$activity=="STANDING",][3:68])
L1 <- colMeans(meanSDTable[meanSDTable$subject==1 & meanSDTable$activity=="LAYING",][3:68])
W2 <- colMeans(meanSDTable[meanSDTable$subject==2 & meanSDTable$activity=="WALKING",][3:68])
WU2 <- colMeans(meanSDTable[meanSDTable$subject==2 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD2 <- colMeans(meanSDTable[meanSDTable$subject==2 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI2 <- colMeans(meanSDTable[meanSDTable$subject==2 & meanSDTable$activity=="SITTING",][3:68])
ST2 <- colMeans(meanSDTable[meanSDTable$subject==2 & meanSDTable$activity=="STANDING",][3:68])
L2 <- colMeans(meanSDTable[meanSDTable$subject==2 & meanSDTable$activity=="LAYING",][3:68])
W3 <- colMeans(meanSDTable[meanSDTable$subject==3 & meanSDTable$activity=="WALKING",][3:68])
WU3 <- colMeans(meanSDTable[meanSDTable$subject==3 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD3 <- colMeans(meanSDTable[meanSDTable$subject==3 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI3 <- colMeans(meanSDTable[meanSDTable$subject==3 & meanSDTable$activity=="SITTING",][3:68])
ST3 <- colMeans(meanSDTable[meanSDTable$subject==3 & meanSDTable$activity=="STANDING",][3:68])
L3 <- colMeans(meanSDTable[meanSDTable$subject==3 & meanSDTable$activity=="LAYING",][3:68])
W4 <- colMeans(meanSDTable[meanSDTable$subject==4 & meanSDTable$activity=="WALKING",][3:68])
WU4 <- colMeans(meanSDTable[meanSDTable$subject==4 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD4 <- colMeans(meanSDTable[meanSDTable$subject==4 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI4 <- colMeans(meanSDTable[meanSDTable$subject==4 & meanSDTable$activity=="SITTING",][3:68])
ST4 <- colMeans(meanSDTable[meanSDTable$subject==4 & meanSDTable$activity=="STANDING",][3:68])
L4 <- colMeans(meanSDTable[meanSDTable$subject==4 & meanSDTable$activity=="LAYING",][3:68])
W5 <- colMeans(meanSDTable[meanSDTable$subject==5 & meanSDTable$activity=="WALKING",][3:68])
WU5 <- colMeans(meanSDTable[meanSDTable$subject==5 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD5 <- colMeans(meanSDTable[meanSDTable$subject==5 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI5 <- colMeans(meanSDTable[meanSDTable$subject==5 & meanSDTable$activity=="SITTING",][3:68])
ST5 <- colMeans(meanSDTable[meanSDTable$subject==5 & meanSDTable$activity=="STANDING",][3:68])
L5 <- colMeans(meanSDTable[meanSDTable$subject==5 & meanSDTable$activity=="LAYING",][3:68])
W6 <- colMeans(meanSDTable[meanSDTable$subject==6 & meanSDTable$activity=="WALKING",][3:68])
WU6 <- colMeans(meanSDTable[meanSDTable$subject==6 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD6 <- colMeans(meanSDTable[meanSDTable$subject==6 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI6 <- colMeans(meanSDTable[meanSDTable$subject==6 & meanSDTable$activity=="SITTING",][3:68])
ST6 <- colMeans(meanSDTable[meanSDTable$subject==6 & meanSDTable$activity=="STANDING",][3:68])
L6 <- colMeans(meanSDTable[meanSDTable$subject==6 & meanSDTable$activity=="LAYING",][3:68])
W7 <- colMeans(meanSDTable[meanSDTable$subject==7 & meanSDTable$activity=="WALKING",][3:68])
WU7 <- colMeans(meanSDTable[meanSDTable$subject==7 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD7 <- colMeans(meanSDTable[meanSDTable$subject==7 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI7 <- colMeans(meanSDTable[meanSDTable$subject==7 & meanSDTable$activity=="SITTING",][3:68])
ST7 <- colMeans(meanSDTable[meanSDTable$subject==7 & meanSDTable$activity=="STANDING",][3:68])
L7 <- colMeans(meanSDTable[meanSDTable$subject==7 & meanSDTable$activity=="LAYING",][3:68])
W8 <- colMeans(meanSDTable[meanSDTable$subject==8 & meanSDTable$activity=="WALKING",][3:68])
WU8 <- colMeans(meanSDTable[meanSDTable$subject==8 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD8 <- colMeans(meanSDTable[meanSDTable$subject==8 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI8 <- colMeans(meanSDTable[meanSDTable$subject==8 & meanSDTable$activity=="SITTING",][3:68])
ST8 <- colMeans(meanSDTable[meanSDTable$subject==8 & meanSDTable$activity=="STANDING",][3:68])
L8 <- colMeans(meanSDTable[meanSDTable$subject==8 & meanSDTable$activity=="LAYING",][3:68])
W9 <- colMeans(meanSDTable[meanSDTable$subject==9 & meanSDTable$activity=="WALKING",][3:68])
WU9 <- colMeans(meanSDTable[meanSDTable$subject==9 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD9 <- colMeans(meanSDTable[meanSDTable$subject==9 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI9 <- colMeans(meanSDTable[meanSDTable$subject==9 & meanSDTable$activity=="SITTING",][3:68])
ST9 <- colMeans(meanSDTable[meanSDTable$subject==9 & meanSDTable$activity=="STANDING",][3:68])
L9 <- colMeans(meanSDTable[meanSDTable$subject==9 & meanSDTable$activity=="LAYING",][3:68])
W10 <- colMeans(meanSDTable[meanSDTable$subject==10 & meanSDTable$activity=="WALKING",][3:68])
WU10 <- colMeans(meanSDTable[meanSDTable$subject==10 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD10 <- colMeans(meanSDTable[meanSDTable$subject==10 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI10 <- colMeans(meanSDTable[meanSDTable$subject==10 & meanSDTable$activity=="SITTING",][3:68])
ST10 <- colMeans(meanSDTable[meanSDTable$subject==10 & meanSDTable$activity=="STANDING",][3:68])
L10 <- colMeans(meanSDTable[meanSDTable$subject==10 & meanSDTable$activity=="LAYING",][3:68])
W11 <- colMeans(meanSDTable[meanSDTable$subject==11 & meanSDTable$activity=="WALKING",][3:68])
WU11 <- colMeans(meanSDTable[meanSDTable$subject==11 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD11 <- colMeans(meanSDTable[meanSDTable$subject==11 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI11 <- colMeans(meanSDTable[meanSDTable$subject==11 & meanSDTable$activity=="SITTING",][3:68])
ST11 <- colMeans(meanSDTable[meanSDTable$subject==11 & meanSDTable$activity=="STANDING",][3:68])
L11 <- colMeans(meanSDTable[meanSDTable$subject==11 & meanSDTable$activity=="LAYING",][3:68])
W12 <- colMeans(meanSDTable[meanSDTable$subject==12 & meanSDTable$activity=="WALKING",][3:68])
WU12 <- colMeans(meanSDTable[meanSDTable$subject==12 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD12 <- colMeans(meanSDTable[meanSDTable$subject==12 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI12 <- colMeans(meanSDTable[meanSDTable$subject==12 & meanSDTable$activity=="SITTING",][3:68])
ST12 <- colMeans(meanSDTable[meanSDTable$subject==12 & meanSDTable$activity=="STANDING",][3:68])
L12 <- colMeans(meanSDTable[meanSDTable$subject==12 & meanSDTable$activity=="LAYING",][3:68])
W13 <- colMeans(meanSDTable[meanSDTable$subject==13 & meanSDTable$activity=="WALKING",][3:68])
WU13 <- colMeans(meanSDTable[meanSDTable$subject==13 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD13 <- colMeans(meanSDTable[meanSDTable$subject==13 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI13 <- colMeans(meanSDTable[meanSDTable$subject==13 & meanSDTable$activity=="SITTING",][3:68])
ST13 <- colMeans(meanSDTable[meanSDTable$subject==13 & meanSDTable$activity=="STANDING",][3:68])
L13 <- colMeans(meanSDTable[meanSDTable$subject==13 & meanSDTable$activity=="LAYING",][3:68])
W14 <- colMeans(meanSDTable[meanSDTable$subject==14 & meanSDTable$activity=="WALKING",][3:68])
WU14 <- colMeans(meanSDTable[meanSDTable$subject==14 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD14 <- colMeans(meanSDTable[meanSDTable$subject==14 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI14 <- colMeans(meanSDTable[meanSDTable$subject==14 & meanSDTable$activity=="SITTING",][3:68])
ST14 <- colMeans(meanSDTable[meanSDTable$subject==14 & meanSDTable$activity=="STANDING",][3:68])
L14 <- colMeans(meanSDTable[meanSDTable$subject==14 & meanSDTable$activity=="LAYING",][3:68])
W15 <- colMeans(meanSDTable[meanSDTable$subject==15 & meanSDTable$activity=="WALKING",][3:68])
WU15 <- colMeans(meanSDTable[meanSDTable$subject==15 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD15 <- colMeans(meanSDTable[meanSDTable$subject==15 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI15 <- colMeans(meanSDTable[meanSDTable$subject==15 & meanSDTable$activity=="SITTING",][3:68])
ST15 <- colMeans(meanSDTable[meanSDTable$subject==15 & meanSDTable$activity=="STANDING",][3:68])
L15 <- colMeans(meanSDTable[meanSDTable$subject==15 & meanSDTable$activity=="LAYING",][3:68])
W16 <- colMeans(meanSDTable[meanSDTable$subject==16 & meanSDTable$activity=="WALKING",][3:68])
WU16 <- colMeans(meanSDTable[meanSDTable$subject==16 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD16 <- colMeans(meanSDTable[meanSDTable$subject==16 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI16 <- colMeans(meanSDTable[meanSDTable$subject==16 & meanSDTable$activity=="SITTING",][3:68])
ST16 <- colMeans(meanSDTable[meanSDTable$subject==16 & meanSDTable$activity=="STANDING",][3:68])
L16 <- colMeans(meanSDTable[meanSDTable$subject==16 & meanSDTable$activity=="LAYING",][3:68])
W17 <- colMeans(meanSDTable[meanSDTable$subject==17 & meanSDTable$activity=="WALKING",][3:68])
WU17 <- colMeans(meanSDTable[meanSDTable$subject==17 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD17 <- colMeans(meanSDTable[meanSDTable$subject==17 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI17 <- colMeans(meanSDTable[meanSDTable$subject==17 & meanSDTable$activity=="SITTING",][3:68])
ST17 <- colMeans(meanSDTable[meanSDTable$subject==17 & meanSDTable$activity=="STANDING",][3:68])
L17 <- colMeans(meanSDTable[meanSDTable$subject==17 & meanSDTable$activity=="LAYING",][3:68])
W18 <- colMeans(meanSDTable[meanSDTable$subject==18 & meanSDTable$activity=="WALKING",][3:68])
WU18 <- colMeans(meanSDTable[meanSDTable$subject==18 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD18 <- colMeans(meanSDTable[meanSDTable$subject==18 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI18 <- colMeans(meanSDTable[meanSDTable$subject==18 & meanSDTable$activity=="SITTING",][3:68])
ST18 <- colMeans(meanSDTable[meanSDTable$subject==18 & meanSDTable$activity=="STANDING",][3:68])
L18 <- colMeans(meanSDTable[meanSDTable$subject==18 & meanSDTable$activity=="LAYING",][3:68])
W19 <- colMeans(meanSDTable[meanSDTable$subject==19 & meanSDTable$activity=="WALKING",][3:68])
WU19 <- colMeans(meanSDTable[meanSDTable$subject==19 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD19 <- colMeans(meanSDTable[meanSDTable$subject==19 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI19 <- colMeans(meanSDTable[meanSDTable$subject==19 & meanSDTable$activity=="SITTING",][3:68])
ST19 <- colMeans(meanSDTable[meanSDTable$subject==19 & meanSDTable$activity=="STANDING",][3:68])
L19 <- colMeans(meanSDTable[meanSDTable$subject==19 & meanSDTable$activity=="LAYING",][3:68])
W20 <- colMeans(meanSDTable[meanSDTable$subject==20 & meanSDTable$activity=="WALKING",][3:68])
WU20 <- colMeans(meanSDTable[meanSDTable$subject==20 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD20 <- colMeans(meanSDTable[meanSDTable$subject==20 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI20 <- colMeans(meanSDTable[meanSDTable$subject==20 & meanSDTable$activity=="SITTING",][3:68])
ST20 <- colMeans(meanSDTable[meanSDTable$subject==20 & meanSDTable$activity=="STANDING",][3:68])
L20 <- colMeans(meanSDTable[meanSDTable$subject==20 & meanSDTable$activity=="LAYING",][3:68])
W21 <- colMeans(meanSDTable[meanSDTable$subject==21 & meanSDTable$activity=="WALKING",][3:68])
WU21 <- colMeans(meanSDTable[meanSDTable$subject==21 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD21 <- colMeans(meanSDTable[meanSDTable$subject==21 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI21 <- colMeans(meanSDTable[meanSDTable$subject==21 & meanSDTable$activity=="SITTING",][3:68])
ST21 <- colMeans(meanSDTable[meanSDTable$subject==21 & meanSDTable$activity=="STANDING",][3:68])
L21 <- colMeans(meanSDTable[meanSDTable$subject==21 & meanSDTable$activity=="LAYING",][3:68])
W22 <- colMeans(meanSDTable[meanSDTable$subject==22 & meanSDTable$activity=="WALKING",][3:68])
WU22 <- colMeans(meanSDTable[meanSDTable$subject==22 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD22 <- colMeans(meanSDTable[meanSDTable$subject==22 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI22 <- colMeans(meanSDTable[meanSDTable$subject==22 & meanSDTable$activity=="SITTING",][3:68])
ST22 <- colMeans(meanSDTable[meanSDTable$subject==22 & meanSDTable$activity=="STANDING",][3:68])
L22 <- colMeans(meanSDTable[meanSDTable$subject==22 & meanSDTable$activity=="LAYING",][3:68])
W23 <- colMeans(meanSDTable[meanSDTable$subject==23 & meanSDTable$activity=="WALKING",][3:68])
WU23 <- colMeans(meanSDTable[meanSDTable$subject==23 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD23 <- colMeans(meanSDTable[meanSDTable$subject==23 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI23 <- colMeans(meanSDTable[meanSDTable$subject==23 & meanSDTable$activity=="SITTING",][3:68])
ST23 <- colMeans(meanSDTable[meanSDTable$subject==23 & meanSDTable$activity=="STANDING",][3:68])
L23 <- colMeans(meanSDTable[meanSDTable$subject==23 & meanSDTable$activity=="LAYING",][3:68])
W24 <- colMeans(meanSDTable[meanSDTable$subject==24 & meanSDTable$activity=="WALKING",][3:68])
WU24 <- colMeans(meanSDTable[meanSDTable$subject==24 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD24 <- colMeans(meanSDTable[meanSDTable$subject==24 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI24 <- colMeans(meanSDTable[meanSDTable$subject==24 & meanSDTable$activity=="SITTING",][3:68])
ST24 <- colMeans(meanSDTable[meanSDTable$subject==24 & meanSDTable$activity=="STANDING",][3:68])
L24 <- colMeans(meanSDTable[meanSDTable$subject==24 & meanSDTable$activity=="LAYING",][3:68])
W25 <- colMeans(meanSDTable[meanSDTable$subject==25 & meanSDTable$activity=="WALKING",][3:68])
WU25 <- colMeans(meanSDTable[meanSDTable$subject==25 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD25 <- colMeans(meanSDTable[meanSDTable$subject==25 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI25 <- colMeans(meanSDTable[meanSDTable$subject==25 & meanSDTable$activity=="SITTING",][3:68])
ST25 <- colMeans(meanSDTable[meanSDTable$subject==25 & meanSDTable$activity=="STANDING",][3:68])
L25 <- colMeans(meanSDTable[meanSDTable$subject==25 & meanSDTable$activity=="LAYING",][3:68])
W26 <- colMeans(meanSDTable[meanSDTable$subject==26 & meanSDTable$activity=="WALKING",][3:68])
WU26 <- colMeans(meanSDTable[meanSDTable$subject==26 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD26 <- colMeans(meanSDTable[meanSDTable$subject==26 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI26 <- colMeans(meanSDTable[meanSDTable$subject==26 & meanSDTable$activity=="SITTING",][3:68])
ST26 <- colMeans(meanSDTable[meanSDTable$subject==26 & meanSDTable$activity=="STANDING",][3:68])
L26 <- colMeans(meanSDTable[meanSDTable$subject==26 & meanSDTable$activity=="LAYING",][3:68])
W27 <- colMeans(meanSDTable[meanSDTable$subject==27 & meanSDTable$activity=="WALKING",][3:68])
WU27 <- colMeans(meanSDTable[meanSDTable$subject==27 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD27 <- colMeans(meanSDTable[meanSDTable$subject==27 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI27 <- colMeans(meanSDTable[meanSDTable$subject==27 & meanSDTable$activity=="SITTING",][3:68])
ST27 <- colMeans(meanSDTable[meanSDTable$subject==27 & meanSDTable$activity=="STANDING",][3:68])
L27 <- colMeans(meanSDTable[meanSDTable$subject==27 & meanSDTable$activity=="LAYING",][3:68])
W28 <- colMeans(meanSDTable[meanSDTable$subject==28 & meanSDTable$activity=="WALKING",][3:68])
WU28 <- colMeans(meanSDTable[meanSDTable$subject==28 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD28 <- colMeans(meanSDTable[meanSDTable$subject==28 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI28 <- colMeans(meanSDTable[meanSDTable$subject==28 & meanSDTable$activity=="SITTING",][3:68])
ST28 <- colMeans(meanSDTable[meanSDTable$subject==28 & meanSDTable$activity=="STANDING",][3:68])
L28 <- colMeans(meanSDTable[meanSDTable$subject==28 & meanSDTable$activity=="LAYING",][3:68])
W29 <- colMeans(meanSDTable[meanSDTable$subject==29 & meanSDTable$activity=="WALKING",][3:68])
WU29 <- colMeans(meanSDTable[meanSDTable$subject==29 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD29<- colMeans(meanSDTable[meanSDTable$subject==29 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI29 <- colMeans(meanSDTable[meanSDTable$subject==29 & meanSDTable$activity=="SITTING",][3:68])
ST29 <- colMeans(meanSDTable[meanSDTable$subject==29 & meanSDTable$activity=="STANDING",][3:68])
L29 <- colMeans(meanSDTable[meanSDTable$subject==29 & meanSDTable$activity=="LAYING",][3:68])
W30 <- colMeans(meanSDTable[meanSDTable$subject==30 & meanSDTable$activity=="WALKING",][3:68])
WU30 <- colMeans(meanSDTable[meanSDTable$subject==30 & meanSDTable$activity=="WALKING_UPSTAIRS",][3:68])
WD30 <- colMeans(meanSDTable[meanSDTable$subject==30 & meanSDTable$activity=="WALKING_DOWNSTAIRS",][3:68])
SI30 <- colMeans(meanSDTable[meanSDTable$subject==30 & meanSDTable$activity=="SITTING",][3:68])
ST30 <- colMeans(meanSDTable[meanSDTable$subject==30 & meanSDTable$activity=="STANDING",][3:68])
L30 <- colMeans(meanSDTable[meanSDTable$subject==30 & meanSDTable$activity=="LAYING",][3:68])

#Step 6: Creating a new table from the subsets.

subjectseq <- seq(1,30,1)
subjectcol <- rep(subjectseq,each=6)
activityseq <- c("WALKING", "WALKING_UPSTAIRS", "WALKING DOWNSTAIRS", "SITIING", "STANDING", "LAYING")
activitycol <- rep(activityseq, times=30)

meanbind <- data.frame()
meanbind <- rbind(W1, WU1, WD1, SI1, ST1, L1, W2, WU2, WD2, SI2, ST2, L2, W3, WU3, WD3, SI3, ST3, L3, W4, WU4, WD4, SI4, ST4, L4, W5, WU5, WD5, SI5, ST5, L5, W6, WU6, WD6, SI6, ST6, L6, W7, WU7, WD7, SI7, ST7, L7, W8, WU8, WD8, SI8, ST8, L8, W9, WU9, WD9, SI9, ST9, L9, W10, WU10, WD10, SI10, ST10, L10, W11, WU11, WD11, SI11, ST11, L11, W12, WU12, WD12, SI12, ST12, L12,W13, WU13, WD13, SI13, ST13, L13, W14, WU14, WD14, SI14, ST14, L14, W15, WU15, WD15, SI15, ST15, L15, W16, WU16, WD16, SI16, ST16, L16, W17, WU17, WD17, SI17, ST17, L17, W18, WU18, WD18, SI18, ST18, L18, W19, WU19, WD19, SI19, ST19, L19, W20, WU20, WD20, SI20, ST20, L20,W21, WU21, WD21, SI21, ST21, L21, W22, WU22, WD22, SI22, ST22, L22, W23, WU23, WD23, SI23, ST23, L23, W24, WU24, WD24, SI24, ST24, L24,W25, WU25, WD25, SI25, ST25, L25, W26, WU26, WD26, SI26, ST26, L26, W27, WU27, WD27, SI27, ST27, L27, W28, WU28, WD28, SI28, ST28, L28, W29, WU29, WD29, SI29, ST29, L29, W30, WU30, WD30, SI30, ST30, L30)


finaltable <-cbind.data.frame(subjectcol, activitycol, meanbind)

#Step 7: Outputting table file

write.table(finaltable, "tidydata.txt", row.names = FALSE)
